### ISSUE TITLE
Mobile Meta Tag

### ISSUE THREAD

**Issue by Mikeysax** [Nikkovichert/splurty#1]
On mobile things don't look as good as they could be.
One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.
Let me know in the comments once you figured that step out :)

**Comment by Nikkovichert** [comment]
I think I've fixed it, but not totally sure. I've also reached my concurrent build limit for heroku, so can't see the results.

**Comment by Mikeysax** [comment]
I believe the Heroku limit is due to a server issue on Heroku's side.

Good job adding the meta tag 👍

**Comment by Nikkovichert** [comment]
Great, thank you!
